### ISSUE TITLE
Model not globally exposed

### ISSUE THREAD

**Issue by Nishchit14** [trailsjs/trailpack-mongoose#27]
@konstantinzolotarev @jaumard 
In version 2.0.0
`this.app.orm.User` and `User.` both are undefined :(

It is not exposing `Model` globally as per Trails's v2-latest standards.

**Comment by jaumard** [comment]
Models are not expose globally, only trails model class is exposed globally if I'm not wrong

**Comment by jaumard** [comment]
It's this.app.orm.User right ? Should work normally

**Comment by Nishchit14** [comment]
@jaumard 
Yes, It is `this.app.orm.User`. not working

**Comment by jaumard** [comment]
Test are still passing on Travis for the v2 version, maybe you miss to export your User model on the index.js file ? Or something like this ? Can you give more info on your use case please. As I don't know mongoose I may not be very helpful on this ^^

**Comment by konstantinzolotarev** [comment]
@Nishchit14 Did you fix issue ? If not could you provide us with a bit more details ?

**Comment by Nishchit14** [comment]
@konstantinzolotarev
Yes, It's working now. 

But `yo trails` crashing. 
Due to crash `controllers`, `policies` and `config/web.js` are not being generated.
Also `express`, `trailpack-express` and `trailpack-mongoose` are not auto installing.

**Comment by jaumard** [comment]
Closing this as it fix :) @Nishchit14 I think the other problem come from the generator not this repo
