### ISSUE TITLE
Declare relationship one-to-many

### ISSUE THREAD

**Issue by hoangzinh** [trailsjs/trailpack-mongoose#32]
**VERSIONS**
Trailpack-mongoose: 2.1.0
Trailpack-express: 2.0.3
Trailpack-footprints: 2.0.0,

***DETAIL***
Follow documentation on Trailpack-mongoose and Mongoose itself. If we want to declare relationship between one-to-many. We can do as follow:
```
static schema (app, Mongoose) {
    return {
      childs: [{
        type: Mongoose.Schema.ObjectId,
        ref: 'UserSchema'
      }],
    }
  }
```

But I always get errors to 
```
Error: No such reference exist
    at FootprintService.createAssociation
```
When I try make a request to `/user/:id/childs`

It works only I  update the User schema to
```
     childs: {
        type: [ Mongoose.Schema.ObjectId ],
        ref: 'UserSchema'
      }
```

Do we have different convention with mongoose when declare relationship one-to-many?

**Comment by konstantinzolotarev** [comment]
@hoangzinh To be honest I never used such definition.
Sorry for that.
I'll push a fix asap
